name: check 

on:
 pull_request:
   branches:
     - master
   types: [opened]

jobs:
  commithistory:
    name: action1
    runs-on: ubuntu- 18.04
    steps: 
      - name: abc
        id: checkc
        run: |-
          if  [[git log -1 | grep int1 ]]
          then
            echo ***commit history contains int1***
            exit 0
          fi
    
